background = 151515
foreground = d4d4d4
selection-background = 6a8a6a
selection-foreground = fafafa
cursor-color = 7A7A7A
cursor-text = 000000
split-divider-color = 5a6b7c

# black
palette = 0=#303030
palette = 8=#151515
# red
palette = 1=#f57a7a
palette = 9=#ff9e8b
# green
palette = 2=#7eab8e
palette = 10=#9db89c
# yellow
palette = 3=#fff2af
palette = 11=#d4a017
# blue
palette = 4=#5d6d7e
palette = 12=#b6c8d9
# magenta
palette = 5=#c678dd
palette = 13=#c38b9e
# cyan
palette = 6=#79a0aa
palette = 14=#8dd3c3
# white
palette = 7=#d4d4d4
palette = 15=#fafafa
